// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbsgswwrtorsqylfvlot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRic2dzd3dydG9yc3F5bGZ2bG90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwMzU3ODcsImV4cCI6MjA1NDYxMTc4N30.8J8O8eTfeantGo69WEBgLsFXHpebi4n7wmTPNaEBzDw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);