export enum FishType {
  BabyHammerheadShark = "Baby Hammerhead Shark",
  MiddleHammerheadShark = "Middle Hammerhead Shark",
  AdultHammerheadShark = "Adult Hammerhead Shark",
  BabyGoldfish = "Baby Goldfish",
  NormalGoldfish = "Normal Goldfish",
  GoldfishKoiFish = "Goldfish Koi Fish",
  BabyTurtle = "Baby Turtle",
  EvolvedTurtle = "Evolved Turtle",
  BabyPufferfish = "Baby Pufferfish",
  EvolvedPufferfish = "Evolved Pufferfish",
  BabyDolphin = "Baby Dolphin",
  AdultDolphin = "Adult Dolphin",
  BabyGreatWhiteShark = "Baby Great White Shark",
  EvolvedGreatWhiteShark = "Evolved Great White Shark",
  BabyWhale = "Baby Whale",
  EvolvedBabyWhale = "Evolved Baby Whale",
}

export type FishInfo = {
  id: number;
  name: string;
  rarity: string;
  level: number;
  emoji: string;
  description: string;
  habitat: string;
  population?: string;
  conservationStatus?: string;
};

// Your fishData, including Baby Whale (ID=15).
export const fishData: FishInfo[] = [
  {
    id: 1,
    name: "Pixel Puffer",
    rarity: "Common",
    level: 5,
    emoji: "🐡",
    description: "A spiky friend with attitude",
    habitat: "Coral Reefs",
    population: "Stable in most reefs",
    conservationStatus: "Not currently threatened",
  },
  {
    id: 2,
    name: "Baby Hammerhead Shark",
    rarity: "Uncommon",
    level: 3,
    emoji: "🦈",
    description: "A young hammerhead with a curious nature",
    habitat: "Coastal Waters",
    population: "Stable",
    conservationStatus: "Not currently threatened",
  },
  {
    id: 3,
    name: "Middle Hammerhead Shark",
    rarity: "Uncommon",
    level: 5,
    emoji: "🦈",
    description: "A growing hammerhead with a keen sense of direction",
    habitat: "Coastal Waters",
    population: "Stable",
    conservationStatus: "Not currently threatened",
  },
  {
    id: 4,
    name: "Adult Hammerhead Shark",
    rarity: "Rare",
    level: 8,
    emoji: "🦈",
    description: "A fully grown hammerhead, master of its domain",
    habitat: "Open Ocean",
    population: "Stable",
    conservationStatus: "Not currently threatened",
  },
  {
    id: 5,
    name: "Baby Goldfish",
    rarity: "Common",
    level: 1,
    emoji: "🐟",
    description: "A tiny goldfish with a lot of potential",
    habitat: "Freshwater Ponds",
    population: "Abundant",
    conservationStatus: "Not currently threatened",
  },
  {
    id: 6,
    name: "Normal Goldfish",
    rarity: "Common",
    level: 2,
    emoji: "🐟",
    description: "A regular goldfish, often found in home aquariums",
    habitat: "Freshwater Ponds",
    population: "Abundant",
    conservationStatus: "Not currently threatened",
  },
  {
    id: 7,
    name: "Goldfish Koi Fish",
    rarity: "Uncommon",
    level: 4,
    emoji: "🐟",
    description: "A beautiful hybrid of goldfish and koi",
    habitat: "Garden Ponds",
    population: "Stable",
    conservationStatus: "Not currently threatened",
  },
  {
    id: 8,
    name: "Baby Turtle",
    rarity: "Common",
    level: 1,
    emoji: "🐢",
    description: "A small turtle just starting its journey",
    habitat: "Coastal Waters",
    population: "Stable",
    conservationStatus: "Not currently threatened",
  },
  {
    id: 9,
    name: "Evolved Turtle",
    rarity: "Rare",
    level: 6,
    emoji: "🐢",
    description: "A wise and experienced turtle",
    habitat: "Coastal Waters",
    population: "Stable",
    conservationStatus: "Not currently threatened",
  },
  {
    id: 10,
    name: "Baby Pufferfish",
    rarity: "Common",
    level: 2,
    emoji: "🐡",
    description: "A small pufferfish with a big personality",
    habitat: "Coral Reefs",
    population: "Stable",
    conservationStatus: "Not currently threatened",
  },
  {
    id: 11,
    name: "Evolved Pufferfish",
    rarity: "Uncommon",
    level: 5,
    emoji: "🐡",
    description: "A larger pufferfish with more spikes",
    habitat: "Coral Reefs",
    population: "Stable",
    conservationStatus: "Not currently threatened",
  },
  {
    id: 12,
    name: "Baby Dolphin",
    rarity: "Rare",
    level: 3,
    emoji: "🐬",
    description: "A playful and intelligent young dolphin",
    habitat: "Open Ocean",
    population: "Stable",
    conservationStatus: "Not currently threatened",
  },
  {
    id: 13,
    name: "Adult Dolphin",
    rarity: "Legendary",
    level: 7,
    emoji: "🐬",
    description: "A fully grown dolphin, master of acrobatics",
    habitat: "Open Ocean",
    population: "Stable",
    conservationStatus: "Not currently threatened",
  },
  {
    id: 14,
    name: "Baby Great White Shark",
    rarity: "Legendary",
    level: 10,
    emoji: "🦈",
    description: "A fearsome but adorable apex predator",
    habitat: "Open Ocean",
    population: "Unknown",
    conservationStatus: "Data Missing",
  },
  {
    id: 15,
    name: "Baby Whale",
    rarity: "Rare",
    level: 1,
    emoji: "🐋",
    description: "A small yet mighty whale in training",
    habitat: "Deep Ocean",
    population: "Unknown",
    conservationStatus: "Data Missing",
  },
  {
    id: 16,
    name: "Evolved Baby Whale",
    rarity: "Epic",
    level: 8,
    emoji: "🐋",
    description: "A larger whale with more experience",
    habitat: "Deep Ocean",
    population: "Unknown",
    conservationStatus: "Data Missing",
  },
];
